### ISSUE TITLE
Plugin should not run when running poetry "self" commands

### ISSUE THREAD

**Issue by kohlerj** [vstrimaitis/poetry-pre-commit-plugin#1]
I just encountered what I think is an issue when running `poetry self add` commands.

Since self add commands inherit from add commands, the plugin is started for them as well.

Note that this also applies to self install commands obviously...

I would expect the plugin not to run on these commands since it is not targeting the "output" project but the tool itself, that is poetry.

What do you think?

Thanks for the plugin by the way!

Happy to take care of it if you accept PRs 😄

**Comment by vstrimaitis** [comment]
Hi! Sorry for the delay, GitHub decided to not send me a notification for some reason 😁 

Your suggestion definitely makes sense, and I see you've already submitted a PR - sweet! I'll try to take a look later today.

**Comment by vstrimaitis** [comment]
The new version (`0.1.2`) has been released! 🎉  Thanks again! 😁
